[package]
name = "packe"
version = "0.1.0"
edition = "2021"

[dependencies]
arbitrary = { version = "1.3.2", optional = true}
base64 = "0.22.0"
deadpool = "0.10.0"
deadpool-runtime = "0.1.3"
deadpool-sync = "0.1.2"
lazy_static = "1.4.0"
md-5 = "0.10.6"
native-tls = "0.2.11"
quick-xml = "0.31.0"
rand = "0.8.5"
rods_prot_msg = { path = "../rods_prot_msg/" }
serde = "1.0.197"
serde_json = "1.0.114"

[features]
arbitrary = [ "dep:arbitrary" ]
