[package]
name = "packe"
version = "0.1.0"
edition = "2021"

[dependencies]
arbitrary = { version = "1.3.2", optional = true}
quick-xml = "0.31.0"
rods_prot_msg = { path = "../rods_prot_msg/" }

[features]
arbitrary = [ "dep:arbitrary" ]
