pub enum KeyWord {
    AllKw,
    CopiesKw,
    ExecLocallyKw,
    ForceFlagKw,
    CliInSvrFirewallKw,
    RegChksumKw,
    VerifyChksumKw,
    VerifyBySizeKw,
    ObjPathKw,
    RescNameKw,
    DestRescNameKw,
    DefRescNameKw,
    BackupRescNameKw,
    LeafResourceNameKw,
    DataTypeKw,
    DataSizeKw,
    ChksumKw,
    OrigChksumKw,
    VersionKw,
    FilePathKw,
    BunFilePathKw,
    ReplNumKw,
    WriteFlagKw,
    ReplStatusKw,
    AllReplStatusKw,
    MetadataIncludedKw,
    AclIncludedKw,
    DataIncludedKw,
    DataOwnerKw,
    DataOwnerZoneKw,
    DataExpiryKw,
    DataCommentsKw,
    DataCreateKw,
    DataModifyKw,
    DataAccessKw,
    DataAccessInxKw,
    NoOpenFlagKw,
    PhyopenBySizeKw,
    StreamingKw,
    DataIdKw,
    CollIdKw,
    DataModeKw,
    DataNameKw,
    StatusStringKw,
    DataMapIdKw,
    NoParaOpKw,
    LocalPathKw,
    RsyncModeKw,
    RsyncDestPathKw,
    RsyncChksumKw,
    ChksumAllKw,
    ForceChksumKw,
    CollectionKw,
    AdminKw,
    AdminRmtrashKw,
    UnregKw,
    RmtrashKw,
    RecursiveOprKw,
    CollectionTypeKw,
    CollectionInfo1Kw,
    CollectionInfo2Kw,
    CollectionMtimeKw,
    SelObjTypeKw,
    StructFileOprKw,
    AllMsParamKw,
    UnregCollKw,
    UpdateReplKw,
    RbudpTransferKw,
    VeryVerboseKw,
    RbudpSendRateKw,
    RbudpPackSizeKw,
    ZoneKw,
    RemoteZoneOprKw,
    ReplDataObjInpKw,
    CrossZoneCreateKw,
    VerifyVaultSizeEqualsDatabaseSizeKw,
    QueryByDataIdKw,
    SuClientUserKw,
    RmBunCopyKw,
    KeyWordKw,
    CreateModeKw,
    OpenFlagsKw,
    OffsetKw,
    NumThreadsKw,
    OprTypeKw,
    OpenTypeKw,
    CollFlagsKw,
    TranslatedPathKw,
    NoTranslateLinkptKw,
    BulkOprKw,
    NonBulkOprKw,
    ExecCmdRuleKw,
    ExecMyRuleKw,
    StreamStdoutKw,
    RegReplKw,
    AgeKw,
    DryrunKw,
    NoComputeKw,
    AclCollectionKw,
    NoChkCopyLenKw,
    TicketKw,
    PurgeCacheKw,
    EmptyBundleOnlyKw,
    ReplicaTokenKw,
    RegisterAsIntermediateKw,
    StaleAllIntermediateReplicasKw,
    SourceL1DescKw,
    LockTypeKw,
    LockCmdKw,
    LockFdKw,
    MaxSubFileKw,
    MaxBundleSizeKw,
    NoStagingKw,
    MaxSubFileKw,
    FileUidKw,
    FileOwnerKw,
    FileGidKw,
    FileGroupKw,
    FileModeKw,
    FileCtimeKw,
    FileMtimeKw,
    FileSourcePathKw,
    ExcludeFileKw,
    GetResourceInfoOpTypeKw,
    RescZoneKw,
    RescLocKw,
    RescTypeKw,
    RescClassKw,
    RescVaultPathKw,
    RescStatusKw,
    GatewayAddrKw,
    RescMaxObjSizeKw,
    FreeSpaceKw,
    FreeSpaceTimeKw,
    FreeSpaceTimestampKw,
    QuotaLimitKw,
    RescInfoKw,
    RescTypeInxKw,
    RescClassInxKw,
    RescIdKw,
    RescCommentsKw,
    RescCreateKw,
    RescModifyKw,
    UserNameClientKw,
    RodsZoneClientKw,
    HostClientKw,
    ClientAddrKw,
    UserTypeClientKw,
    AuthStrClientKw,
    UserAuthSchemeClientKw,
    UserInfoClientKw,
    UserCommentClientKw,
    UserCreateClientKw,
    UserModifyClientKw,
    UserNameProxyKw,
    RodsZoneProxyKw,
    HostProxyKw,
    UserTypeProxyKw,
    AuthStrProxyKw,
    UserAuthSchemeProxyKw,
    UserInfoProxyKw,
    UserCommentProxyKw,
    UserCreateProxyKw,
    UserModifyProxyKw,
    AccessPermissionKw,
    NoChkFilePermKw,
    CollNameKw,
    CollParentNameKw,
    CollOwnerNameKw,
    CollOwnerZoneKw,
    CollMapIdKw,
    CollInheritanceKw,
    CollCommentsKw,
    CollExpiryKw,
    CollCreateKw,
    CollModifyKw,
    CollAccessKw,
    CollAccessInxKw,
    CollIdKw,
    RuleNameKw,
    RuleReiFilePathKw,
    RuleUserNameKw,
    RuleExeAddressKw,
    RuleExeTimeKw,
    RuleExeFrequencyKw,
    RulePriorityKw,
    RuleEstimateExeTimeKw,
    RuleNotificationAddrKw,
    RuleLastExeTimeKw,
    RuleExeStatusKw,
    RuleExecutionContextKw,
    ExcludeFileKw,
    AgeKw,
    RescHierStrKw,
    DestRescHierStrKw,
    InPdmoKw,
    StageObjKw,
    SyncObjKw,
    InReplKw,
    SocketHandleKw,
    SslHostKw,
    SslSharedSecretKw,
    SslKeySizeKw,
    SslSaltSizeKw,
    SslNumHashRoundsKw,
    SslAlgorithmKw,
    PhysicalPathKw,
    ModeKw,
    FlagsKw,
    ObjCountKw,
    LogicalPathKw,
    FileDescriptorKw,
    L1DescIdxKw,
    SizeKw,
    ReplRequestedKw,
    HostAddrKw,
    ZoneNameKw,
    PortNumKw,
    SubFilePathKw,
    SpecCollClassKw,
    SpecCollTypeKw,
    SpecCollObjPathKw,
    SpecCollResourceKw,
    SpecCollRescHierKw,
    SpecCollPhyPathKw,
    SpecCollCacheDirKw,
    SpecCollCacheDirty,
    SpecCollReplNum,
    KeyValuePassthroughKw,
    DisableStrictAclKw,
    InstanceNameKw,
    SetTimeToNowKw,
    SelectedHierarchyKw,
    FileModifiedKw,
    BundleResc,
    BundleStr,
    BundleRescClass,
    AvailableKw,
    KwSwitchProxyUser,
    KwCloseOpenReplicas,
    KwKeepSvrToSvrConnections,
}

impl From<&str> for KeyWord {
    fn from(s: &str) -> Self {
        match s {
            "all" => KeyWord::AllKw,
            "copies" => KeyWord::CopiesKw,
            "execLocally" => KeyWord::ExecLocallyKw,
            "forceFlag" => KeyWord::ForceFlagKw,
            "cliInSvrFirewall" => KeyWord::CliInSvrFirewallKw,
            "regChksum" => KeyWord::RegChksumKw,
            "verifyChksum" => KeyWord::VerifyChksumKw,
            "verifyBySize" => KeyWord::VerifyBySizeKw,
            "objPath" => KeyWord::ObjPathKw,
            "rescName" => KeyWord::RescNameKw,
            "destRescName" => KeyWord::DestRescNameKw,
            "defRescName" => KeyWord::DefRescNameKw,
            "backupRescName" => KeyWord::BackupRescNameKw,
            "leafRescName" => KeyWord::LeafResourceNameKw,
            "dataType" => KeyWord::DataTypeKw,
            "dataSize" => KeyWord::DataSizeKw,
            "chksum" => KeyWord::ChksumKw,
            "orig_chksum" => KeyWord::OrigChksumKw,
            "version" => KeyWord::VersionKw,
            "filePath" => KeyWord::FilePathKw,
            "bunFilePath" => KeyWord::BunFilePathKw,
            "replNum" => KeyWord::ReplNumKw,
            "writeFlag" => KeyWord::WriteFlagKw,
            "replStatus" => KeyWord::ReplStatusKw,
            "allReplStatus" => KeyWord::AllReplStatusKw,
            "metadataIncluded" => KeyWord::MetadataIncludedKw,
            "aclIncluded" => KeyWord::AclIncludedKw,
            "dataIncluded" => KeyWord::DataIncludedKw,
            "dataOwner" => KeyWord::DataOwnerKw,
            "dataOwnerZone" => KeyWord::DataOwnerZoneKw,
            "dataExpiry" => KeyWord::DataExpiryKw,
            "dataComments" => KeyWord::DataCommentsKw,
            "dataCreate" => KeyWord::DataCreateKw,
            "dataModify" => KeyWord::DataModifyKw,
            "dataAccess" => KeyWord::DataAccessKw,
            "dataAccessInx" => KeyWord::DataAccessInxKw,
            "noOpenFlag" => KeyWord::NoOpenFlagKw,
            "phyOpenBySize" => KeyWord::PhyopenBySizeKw,
            "streaming" => KeyWord::StreamingKw,
            "dataId" => KeyWord::DataIdKw,
            "collId" => KeyWord::CollIdKw,
            "dataMode" => KeyWord::DataModeKw,
            "data_name" => KeyWord::DataNameKw,
            "statusString" => KeyWord::StatusStringKw,
            "dataMapId" => KeyWord::DataMapIdKw,
            "noParaOpr" => KeyWord::NoParaOpKw,
            "localPath" => KeyWord::LocalPathKw,
            "rsyncMode" => KeyWord::RsyncModeKw,
            "rsyncDestPath" => KeyWord::RsyncDestPathKw,
            "rsyncChksum" => KeyWord::RsyncChksumKw,
            "ChksumAll" => KeyWord::ChksumAllKw,
            "forceChksum" => KeyWord::ForceChksumKw,
            "collection" => KeyWord::CollectionKw,
            "irodsAdmin" => KeyWord::AdminKw,
            "irodsAdminRmTrash" => KeyWord::AdminRmtrashKw,
            "unreg" => KeyWord::UnregKw,
            "irodsRmTrash" => KeyWord::RmtrashKw,
            "recursiveOpr" => KeyWord::RecursiveOprKw,
            "collectionType" => KeyWord::CollectionTypeKw,
            "collectionInfo1" => KeyWord::CollectionInfo1Kw,
            "collectionInfo2" => KeyWord::CollectionInfo2Kw,
            "collectionMtime" => KeyWord::CollectionMtimeKw,
            "selObjType" => KeyWord::SelObjTypeKw,
            "structFileOpr" => KeyWord::StructFileOprKw,
            "allMsParam" => KeyWord::AllMsParamKw,
            "unregColl" => KeyWord::UnregCollKw,
            "updateRepl" => KeyWord::UpdateReplKw,
            "rbudpTransfer" => KeyWord::RbudpTransferKw,
            "veryVerbose" => KeyWord::VeryVerboseKw,
            "rbudpSendRate" => KeyWord::RbudpSendRateKw,
            "rbudpPackSize" => KeyWord::RbudpPackSizeKw,
            "zone" => KeyWord::ZoneKw,
            "remoteZoneOpr" => KeyWord::RemoteZoneOprKw,
            "replDataObjInp" => KeyWord::ReplDataObjInpKw,
            "replDataObjInp" => KeyWord::CrossZoneCreateKw,
            "verifyVaultSizeEqualsDatabaseSize" => KeyWord::VerifyVaultSizeEqualsDatabaseSizeKw,
            "queryByDataID" => KeyWord::QueryByDataIdKw,
            "suClientUser" => KeyWord::SuClientUserKw,
            "rmBunCopy" => KeyWord::RmBunCopyKw,
            "keyWord" => KeyWord::KeyWordKw,
            "createMode" => KeyWord::CreateModeKw,
            "openFlags" => KeyWord::OpenFlagsKw,
            "offset" => KeyWord::OffsetKw,
            "numThreads" => KeyWord::NumThreadsKw,
            "oprType" => KeyWord::OprTypeKw,
            "openType" => KeyWord::OpenTypeKw,
            "collFlags" => KeyWord::CollFlagsKw,
            "translatedPath" => KeyWord::TranslatedPathKw,
            "noTranslateMntpt" => KeyWord::NoTranslateLinkptKw,
            "bulkOpr" => KeyWord::BulkOprKw,
            "nonBulkOpr" => KeyWord::NonBulkOprKw,
            "execCmdRule" => KeyWord::ExecCmdRuleKw,
            "execMyRule" => KeyWord::ExecMyRuleKw,
            "streamStdout" => KeyWord::StreamStdoutKw,
            "regRepl" => KeyWord::RegReplKw,
            "age" => KeyWord::AgeKw,
            "dryrun" => KeyWord::DryrunKw,
            "no_compute" => KeyWord::NoComputeKw,
            "aclCollection" => KeyWord::AclCollectionKw,
            "noChkCopyLen" => KeyWord::NoChkCopyLenKw,
            "ticket" => KeyWord::TicketKw,
            "purgeCache" => KeyWord::PurgeCacheKw,
            "emptyBundleOnly" => KeyWord::EmptyBundleOnlyKw,
            "replicaToken" => KeyWord::ReplicaTokenKw,
            "registerAsIntermediate" => KeyWord::RegisterAsIntermediateKw,
            "staleAllIntermediateReplicas" => KeyWord::StaleAllIntermediateReplicasKw,
            "sourceL1Desc" => KeyWord::SourceL1DescKw,
            "lockType" => KeyWord::LockTypeKw,
            "lockCmd" => KeyWord::LockCmdKw,
            "lockFd" => KeyWord::LockFdKw,
            "maxSubFile" => KeyWord::MaxSubFileKw,
            "maxBunSize" => KeyWord::MaxBundleSizeKw,
            "noStaging" => KeyWord::NoStagingKw,
            "maxSubFile" => KeyWord::MaxSubFileKw,
            "fileUid" => KeyWord::FileUidKw,
            "fileOwner" => KeyWord::FileOwnerKw,
            "fileGid" => KeyWord::FileGidKw,
            "fileGroup" => KeyWord::FileGroupKw,
            "fileMode" => KeyWord::FileModeKw,
            "fileCtime" => KeyWord::FileCtimeKw,
            "fileMtime" => KeyWord::FileMtimeKw,
            "fileSourcePath" => KeyWord::FileSourcePathKw,
            "excludeFile" => KeyWord::ExcludeFileKw,
            "getResourceInfoOpType" => KeyWord::GetResourceInfoOpTypeKw,
            "zoneName" => KeyWord::RescZoneKw,
            "rescLoc" => KeyWord::RescLocKw,
            "rescType" => KeyWord::RescTypeKw,
            "rescClass" => KeyWord::RescClassKw,
            "rescVaultPath" => KeyWord::RescVaultPathKw,
            "rescStatus" => KeyWord::RescStatusKw,
            "gateWayAddr" => KeyWord::GatewayAddrKw,
            "rescMaxObjSize" => KeyWord::RescMaxObjSizeKw,
            "freeSpace" => KeyWord::FreeSpaceKw,
            "freeSpaceTime" => KeyWord::FreeSpaceTimeKw,
            "freeSpaceTimeStamp" => KeyWord::FreeSpaceTimestampKw,
            "quotaLimit" => KeyWord::QuotaLimitKw,
            "rescInfo" => KeyWord::RescInfoKw,
            "rescTypeInx" => KeyWord::RescTypeInxKw,
            "rescClassInx" => KeyWord::RescClassInxKw,
            "rescId" => KeyWord::RescIdKw,
            "rescComments" => KeyWord::RescCommentsKw,
            "rescCreate" => KeyWord::RescCreateKw,
            "rescModify" => KeyWord::RescModifyKw,
            "userNameClient" => KeyWord::UserNameClientKw,
            "rodsZoneClient" => KeyWord::RodsZoneClientKw,
            "hostClient" => KeyWord::HostClientKw,
            "clientAddr" => KeyWord::ClientAddrKw,
            "userTypeClient" => KeyWord::UserTypeClientKw,
            "authStrClient" => KeyWord::AuthStrClientKw,
            "userAuthSchemeClient" => KeyWord::UserAuthSchemeClientKw,
            "userInfoClient" => KeyWord::UserInfoClientKw,
            "userCommentClient" => KeyWord::UserCommentClientKw,
            "userCreateClient" => KeyWord::UserCreateClientKw,
            "userModifyClient" => KeyWord::UserModifyClientKw,
            "userNameProxy" => KeyWord::UserNameProxyKw,
            "rodsZoneProxy" => KeyWord::RodsZoneProxyKw,
            "hostProxy" => KeyWord::HostProxyKw,
            "userTypeProxy" => KeyWord::UserTypeProxyKw,
            "authStrProxy" => KeyWord::AuthStrProxyKw,
            "userAuthSchemeProxy" => KeyWord::UserAuthSchemeProxyKw,
            "userInfoProxy" => KeyWord::UserInfoProxyKw,
            "userCommentProxy" => KeyWord::UserCommentProxyKw,
            "userCreateProxy" => KeyWord::UserCreateProxyKw,
            "userModifyProxy" => KeyWord::UserModifyProxyKw,
            "accessPermission" => KeyWord::AccessPermissionKw,
            "noChkFilePerm" => KeyWord::NoChkFilePermKw,
            "collName" => KeyWord::CollNameKw,
            "collParentName" => KeyWord::CollParentNameKw,
            "collOwnername" => KeyWord::CollOwnerNameKw,
            "collOwnerZone" => KeyWord::CollOwnerZoneKw,
            "collMapId" => KeyWord::CollMapIdKw,
            "collInheritance" => KeyWord::CollInheritanceKw,
            "collComments" => KeyWord::CollCommentsKw,
            "collExpiry" => KeyWord::CollExpiryKw,
            "collCreate" => KeyWord::CollCreateKw,
            "collModify" => KeyWord::CollModifyKw,
            "collAccess" => KeyWord::CollAccessKw,
            "collAccessInx" => KeyWord::CollAccessInxKw,
            "collId" => KeyWord::CollIdKw,
            "ruleName" => KeyWord::RuleNameKw,
            "reiFilePath" => KeyWord::RuleReiFilePathKw,
            "userName" => KeyWord::RuleUserNameKw,
            "exeAddress" => KeyWord::RuleExeAddressKw,
            "exeTime" => KeyWord::RuleExeTimeKw,
            "exeFrequency" => KeyWord::RuleExeFrequencyKw,
            "priority" => KeyWord::RulePriorityKw,
            "estimateExeTime" => KeyWord::RuleEstimateExeTimeKw,
            "notificationAddr" => KeyWord::RuleNotificationAddrKw,
            "lastExeTime" => KeyWord::RuleLastExeTimeKw,
            "exeStatus" => KeyWord::RuleExeStatusKw,
            "rule_execution_context" => KeyWord::RuleExecutionContextKw,
            "excludeFile" => KeyWord::ExcludeFileKw,
            "age" => KeyWord::AgeKw,
            "resc_hier" => KeyWord::RescHierStrKw,
            "dest_resc_hier" => KeyWord::DestRescHierStrKw,
            "in_pdmo" => KeyWord::InPdmoKw,
            "stage_object" => KeyWord::StageObjKw,
            "sync_object" => KeyWord::SyncObjKw,
            "in_repl" => KeyWord::InReplKw,
            "tcp_socket_handle" => KeyWord::SocketHandleKw,
            "ssl_host" => KeyWord::SslHostKw,
            "ssl_shared_secret" => KeyWord::SslSharedSecretKw,
            "ssl_key_size" => KeyWord::SslKeySizeKw,
            "ssl_salt_size" => KeyWord::SslSaltSizeKw,
            "ssl_num_hash_rounds" => KeyWord::SslNumHashRoundsKw,
            "ssl_algorithm" => KeyWord::SslAlgorithmKw,
            "physical_path" => KeyWord::PhysicalPathKw,
            "mode_kw" => KeyWord::ModeKw,
            "flags_kw" => KeyWord::FlagsKw,
            "object_count" => KeyWord::ObjCountKw,
            "logical_path" => KeyWord::LogicalPathKw,
            "file_descriptor" => KeyWord::FileDescriptorKw,
            "l1_desc_idx" => KeyWord::L1DescIdxKw,
            "file_size" => KeyWord::SizeKw,
            "repl_requested" => KeyWord::ReplRequestedKw,
            "host_addr" => KeyWord::HostAddrKw,
            "zone_name" => KeyWord::ZoneNameKw,
            "port_num" => KeyWord::PortNumKw,
            "sub_file_path" => KeyWord::SubFilePathKw,
            "spec_coll_class" => KeyWord::SpecCollClassKw,
            "spec_coll_type" => KeyWord::SpecCollTypeKw,
            "spec_coll_obj_path" => KeyWord::SpecCollObjPathKw,
            "spec_coll_resource" => KeyWord::SpecCollResourceKw,
            "spec_coll_resc_hier" => KeyWord::SpecCollRescHierKw,
            "spec_coll_phy_path" => KeyWord::SpecCollPhyPathKw,
            "spec_coll_cache_dir" => KeyWord::SpecCollCacheDirKw,
            "spec_coll_cache_dirty" => KeyWord::SpecCollCacheDirty,
            "spec_coll_repl_num" => KeyWord::SpecCollReplNum,
            "key_value_passthrough" => KeyWord::KeyValuePassthroughKw,
            "disable_strict_acls" => KeyWord::DisableStrictAclKw,
            "instance_name" => KeyWord::InstanceNameKw,
            "set" => KeyWord::SetTimeToNowKw,
            "selected_hierarchy" => KeyWord::SelectedHierarchyKw,
            "file_modified" => KeyWord::FileModifiedKw,
            "bundleResc" => KeyWord::BundleResc,
            "bundle" => KeyWord::BundleStr,
            "available" => KeyWord::AvailableKw,
            "switch_proxy_user" => KeyWord::KwSwitchProxyUser,
            "close_open_replicas" => KeyWord::KwCloseOpenReplicas,
            "keep_svr_to_svr_connections" => KeyWord::KwKeepSvrToSvrConnections,
            _ => panic!("Invalid keyword"),
        }
    }
}
impl From<KeyWord> for &str {
    fn from(kw: KeyWord) -> Self {
        match kw {
            KeyWord::AllKw => "all",
            KeyWord::CopiesKw => "copies",
            KeyWord::ExecLocallyKw => "execLocally",
            KeyWord::ForceFlagKw => "forceFlag",
            KeyWord::CliInSvrFirewallKw => "cliInSvrFirewall",
            KeyWord::RegChksumKw => "regChksum",
            KeyWord::VerifyChksumKw => "verifyChksum",
            KeyWord::VerifyBySizeKw => "verifyBySize",
            KeyWord::ObjPathKw => "objPath",
            KeyWord::RescNameKw => "rescName",
            KeyWord::DestRescNameKw => "destRescName",
            KeyWord::DefRescNameKw => "defRescName",
            KeyWord::BackupRescNameKw => "backupRescName",
            KeyWord::LeafResourceNameKw => "leafRescName",
            KeyWord::DataTypeKw => "dataType",
            KeyWord::DataSizeKw => "dataSize",
            KeyWord::ChksumKw => "chksum",
            KeyWord::OrigChksumKw => "orig_chksum",
            KeyWord::VersionKw => "version",
            KeyWord::FilePathKw => "filePath",
            KeyWord::BunFilePathKw => "bunFilePath",
            KeyWord::ReplNumKw => "replNum",
            KeyWord::WriteFlagKw => "writeFlag",
            KeyWord::ReplStatusKw => "replStatus",
            KeyWord::AllReplStatusKw => "allReplStatus",
            KeyWord::MetadataIncludedKw => "metadataIncluded",
            KeyWord::AclIncludedKw => "aclIncluded",
            KeyWord::DataIncludedKw => "dataIncluded",
            KeyWord::DataOwnerKw => "dataOwner",
            KeyWord::DataOwnerZoneKw => "dataOwnerZone",
            KeyWord::DataExpiryKw => "dataExpiry",
            KeyWord::DataCommentsKw => "dataComments",
            KeyWord::DataCreateKw => "dataCreate",
            KeyWord::DataModifyKw => "dataModify",
            KeyWord::DataAccessKw => "dataAccess",
            KeyWord::DataAccessInxKw => "dataAccessInx",
            KeyWord::NoOpenFlagKw => "noOpenFlag",
            KeyWord::PhyopenBySizeKw => "phyOpenBySize",
            KeyWord::StreamingKw => "streaming",
            KeyWord::DataIdKw => "dataId",
            KeyWord::CollIdKw => "collId",
            KeyWord::DataModeKw => "dataMode",
            KeyWord::DataNameKw => "data_name",
            KeyWord::StatusStringKw => "statusString",
            KeyWord::DataMapIdKw => "dataMapId",
            KeyWord::NoParaOpKw => "noParaOpr",
            KeyWord::LocalPathKw => "localPath",
            KeyWord::RsyncModeKw => "rsyncMode",
            KeyWord::RsyncDestPathKw => "rsyncDestPath",
            KeyWord::RsyncChksumKw => "rsyncChksum",
            KeyWord::ChksumAllKw => "ChksumAll",
            KeyWord::ForceChksumKw => "forceChksum",
            KeyWord::CollectionKw => "collection",
            KeyWord::AdminKw => "irodsAdmin",
            KeyWord::AdminRmtrashKw => "irodsAdminRmTrash",
            KeyWord::UnregKw => "unreg",
            KeyWord::RmtrashKw => "irodsRmTrash",
            KeyWord::RecursiveOprKw => "recursiveOpr",
            KeyWord::CollectionTypeKw => "collectionType",
            KeyWord::CollectionInfo1Kw => "collectionInfo1",
            KeyWord::CollectionInfo2Kw => "collectionInfo2",
            KeyWord::CollectionMtimeKw => "collectionMtime",
            KeyWord::SelObjTypeKw => "selObjType",
            KeyWord::StructFileOprKw => "structFileOpr",
            KeyWord::AllMsParamKw => "allMsParam",
            KeyWord::UnregCollKw => "unregColl",
            KeyWord::UpdateReplKw => "updateRepl",
            KeyWord::RbudpTransferKw => "rbudpTransfer",
            KeyWord::VeryVerboseKw => "veryVerbose",
            KeyWord::RbudpSendRateKw => "rbudpSendRate",
            KeyWord::RbudpPackSizeKw => "rbudpPackSize",
            KeyWord::ZoneKw => "zone",
            KeyWord::RemoteZoneOprKw => "remoteZoneOpr",
            KeyWord::ReplDataObjInpKw => "replDataObjInp",
            KeyWord::CrossZoneCreateKw => "replDataObjInp",
            KeyWord::VerifyVaultSizeEqualsDatabaseSizeKw => "verifyVaultSizeEqualsDatabaseSize",
            KeyWord::QueryByDataIdKw => "queryByDataID",
            KeyWord::SuClientUserKw => "suClientUser",
            KeyWord::RmBunCopyKw => "rmBunCopy",
            KeyWord::KeyWordKw => "keyWord",
            KeyWord::CreateModeKw => "createMode",
            KeyWord::OpenFlagsKw => "openFlags",
            KeyWord::OffsetKw => "offset",
            KeyWord::NumThreadsKw => "numThreads",
            KeyWord::OprTypeKw => "oprType",
            KeyWord::OpenTypeKw => "openType",
            KeyWord::CollFlagsKw => "collFlags",
            KeyWord::TranslatedPathKw => "translatedPath",
            KeyWord::NoTranslateLinkptKw => "noTranslateMntpt",
            KeyWord::BulkOprKw => "bulkOpr",
            KeyWord::NonBulkOprKw => "nonBulkOpr",
            KeyWord::ExecCmdRuleKw => "execCmdRule",
            KeyWord::ExecMyRuleKw => "execMyRule",
            KeyWord::StreamStdoutKw => "streamStdout",
            KeyWord::RegReplKw => "regRepl",
            KeyWord::AgeKw => "age",
            KeyWord::DryrunKw => "dryrun",
            KeyWord::NoComputeKw => "no_compute",
            KeyWord::AclCollectionKw => "aclCollection",
            KeyWord::NoChkCopyLenKw => "noChkCopyLen",
            KeyWord::TicketKw => "ticket",
            KeyWord::PurgeCacheKw => "purgeCache",
            KeyWord::EmptyBundleOnlyKw => "emptyBundleOnly",
            KeyWord::ReplicaTokenKw => "replicaToken",
            KeyWord::RegisterAsIntermediateKw => "registerAsIntermediate",
            KeyWord::StaleAllIntermediateReplicasKw => "staleAllIntermediateReplicas",
            KeyWord::SourceL1DescKw => "sourceL1Desc",
            KeyWord::LockTypeKw => "lockType",
            KeyWord::LockCmdKw => "lockCmd",
            KeyWord::LockFdKw => "lockFd",
            KeyWord::MaxSubFileKw => "maxSubFile",
            KeyWord::MaxBundleSizeKw => "maxBunSize",
            KeyWord::NoStagingKw => "noStaging",
            KeyWord::MaxSubFileKw => "maxSubFile",
            KeyWord::FileUidKw => "fileUid",
            KeyWord::FileOwnerKw => "fileOwner",
            KeyWord::FileGidKw => "fileGid",
            KeyWord::FileGroupKw => "fileGroup",
            KeyWord::FileModeKw => "fileMode",
            KeyWord::FileCtimeKw => "fileCtime",
            KeyWord::FileMtimeKw => "fileMtime",
            KeyWord::FileSourcePathKw => "fileSourcePath",
            KeyWord::ExcludeFileKw => "excludeFile",
            KeyWord::GetResourceInfoOpTypeKw => "getResourceInfoOpType",
            KeyWord::RescZoneKw => "zoneName",
            KeyWord::RescLocKw => "rescLoc",
            KeyWord::RescTypeKw => "rescType",
            KeyWord::RescClassKw => "rescClass",
            KeyWord::RescVaultPathKw => "rescVaultPath",
            KeyWord::RescStatusKw => "rescStatus",
            KeyWord::GatewayAddrKw => "gateWayAddr",
            KeyWord::RescMaxObjSizeKw => "rescMaxObjSize",
            KeyWord::FreeSpaceKw => "freeSpace",
            KeyWord::FreeSpaceTimeKw => "freeSpaceTime",
            KeyWord::FreeSpaceTimestampKw => "freeSpaceTimeStamp",
            KeyWord::QuotaLimitKw => "quotaLimit",
            KeyWord::RescInfoKw => "rescInfo",
            KeyWord::RescTypeInxKw => "rescTypeInx",
            KeyWord::RescClassInxKw => "rescClassInx",
            KeyWord::RescIdKw => "rescId",
            KeyWord::RescCommentsKw => "rescComments",
            KeyWord::RescCreateKw => "rescCreate",
            KeyWord::RescModifyKw => "rescModify",
            KeyWord::UserNameClientKw => "userNameClient",
            KeyWord::RodsZoneClientKw => "rodsZoneClient",
            KeyWord::HostClientKw => "hostClient",
            KeyWord::ClientAddrKw => "clientAddr",
            KeyWord::UserTypeClientKw => "userTypeClient",
            KeyWord::AuthStrClientKw => "authStrClient",
            KeyWord::UserAuthSchemeClientKw => "userAuthSchemeClient",
            KeyWord::UserInfoClientKw => "userInfoClient",
            KeyWord::UserCommentClientKw => "userCommentClient",
            KeyWord::UserCreateClientKw => "userCreateClient",
            KeyWord::UserModifyClientKw => "userModifyClient",
            KeyWord::UserNameProxyKw => "userNameProxy",
            KeyWord::RodsZoneProxyKw => "rodsZoneProxy",
            KeyWord::HostProxyKw => "hostProxy",
            KeyWord::UserTypeProxyKw => "userTypeProxy",
            KeyWord::AuthStrProxyKw => "authStrProxy",
            KeyWord::UserAuthSchemeProxyKw => "userAuthSchemeProxy",
            KeyWord::UserInfoProxyKw => "userInfoProxy",
            KeyWord::UserCommentProxyKw => "userCommentProxy",
            KeyWord::UserCreateProxyKw => "userCreateProxy",
            KeyWord::UserModifyProxyKw => "userModifyProxy",
            KeyWord::AccessPermissionKw => "accessPermission",
            KeyWord::NoChkFilePermKw => "noChkFilePerm",
            KeyWord::CollNameKw => "collName",
            KeyWord::CollParentNameKw => "collParentName",
            KeyWord::CollOwnerNameKw => "collOwnername",
            KeyWord::CollOwnerZoneKw => "collOwnerZone",
            KeyWord::CollMapIdKw => "collMapId",
            KeyWord::CollInheritanceKw => "collInheritance",
            KeyWord::CollCommentsKw => "collComments",
            KeyWord::CollExpiryKw => "collExpiry",
            KeyWord::CollCreateKw => "collCreate",
            KeyWord::CollModifyKw => "collModify",
            KeyWord::CollAccessKw => "collAccess",
            KeyWord::CollAccessInxKw => "collAccessInx",
            KeyWord::CollIdKw => "collId",
            KeyWord::RuleNameKw => "ruleName",
            KeyWord::RuleReiFilePathKw => "reiFilePath",
            KeyWord::RuleUserNameKw => "userName",
            KeyWord::RuleExeAddressKw => "exeAddress",
            KeyWord::RuleExeTimeKw => "exeTime",
            KeyWord::RuleExeFrequencyKw => "exeFrequency",
            KeyWord::RulePriorityKw => "priority",
            KeyWord::RuleEstimateExeTimeKw => "estimateExeTime",
            KeyWord::RuleNotificationAddrKw => "notificationAddr",
            KeyWord::RuleLastExeTimeKw => "lastExeTime",
            KeyWord::RuleExeStatusKw => "exeStatus",
            KeyWord::RuleExecutionContextKw => "rule_execution_context",
            KeyWord::ExcludeFileKw => "excludeFile",
            KeyWord::AgeKw => "age",
            KeyWord::RescHierStrKw => "resc_hier",
            KeyWord::DestRescHierStrKw => "dest_resc_hier",
            KeyWord::InPdmoKw => "in_pdmo",
            KeyWord::StageObjKw => "stage_object",
            KeyWord::SyncObjKw => "sync_object",
            KeyWord::InReplKw => "in_repl",
            KeyWord::SocketHandleKw => "tcp_socket_handle",
            KeyWord::SslHostKw => "ssl_host",
            KeyWord::SslSharedSecretKw => "ssl_shared_secret",
            KeyWord::SslKeySizeKw => "ssl_key_size",
            KeyWord::SslSaltSizeKw => "ssl_salt_size",
            KeyWord::SslNumHashRoundsKw => "ssl_num_hash_rounds",
            KeyWord::SslAlgorithmKw => "ssl_algorithm",
            KeyWord::PhysicalPathKw => "physical_path",
            KeyWord::ModeKw => "mode_kw",
            KeyWord::FlagsKw => "flags_kw",
            KeyWord::ObjCountKw => "object_count",
            KeyWord::LogicalPathKw => "logical_path",
            KeyWord::FileDescriptorKw => "file_descriptor",
            KeyWord::L1DescIdxKw => "l1_desc_idx",
            KeyWord::SizeKw => "file_size",
            KeyWord::ReplRequestedKw => "repl_requested",
            KeyWord::HostAddrKw => "host_addr",
            KeyWord::ZoneNameKw => "zone_name",
            KeyWord::PortNumKw => "port_num",
            KeyWord::SubFilePathKw => "sub_file_path",
            KeyWord::SpecCollClassKw => "spec_coll_class",
            KeyWord::SpecCollTypeKw => "spec_coll_type",
            KeyWord::SpecCollObjPathKw => "spec_coll_obj_path",
            KeyWord::SpecCollResourceKw => "spec_coll_resource",
            KeyWord::SpecCollRescHierKw => "spec_coll_resc_hier",
            KeyWord::SpecCollPhyPathKw => "spec_coll_phy_path",
            KeyWord::SpecCollCacheDirKw => "spec_coll_cache_dir",
            KeyWord::SpecCollCacheDirty => "spec_coll_cache_dirty",
            KeyWord::SpecCollReplNum => "spec_coll_repl_num",
            KeyWord::KeyValuePassthroughKw => "key_value_passthrough",
            KeyWord::DisableStrictAclKw => "disable_strict_acls",
            KeyWord::InstanceNameKw => "instance_name",
            KeyWord::SetTimeToNowKw => "set",
            KeyWord::SelectedHierarchyKw => "selected_hierarchy",
            KeyWord::FileModifiedKw => "file_modified",
            KeyWord::BundleResc => "bundleResc",
            KeyWord::BundleStr => "bundle",
            KeyWord::BundleRescClass => "bundle",
            KeyWord::AvailableKw => "available",
            KeyWord::KwSwitchProxyUser => "switch_proxy_user",
            KeyWord::KwCloseOpenReplicas => "close_open_replicas",
            KeyWord::KwKeepSvrToSvrConnections => "keep_svr_to_svr_connections",
        }
    }
}
